name: Generate Matrix Rain
# اجرا روزانه و قابل اجرا دستی
on:
  schedule:
    - cron: "0 0 * * *"    # هر روز ساعت 00:00 UTC
  workflow_dispatch:

# نیازمند اجازه برای نوشتن در repo (مطمئن می‌شه فایل SVG می‌تونه commit بشه)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update Matrix Rain'
          MAX_LINES: 1000
